services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: "8333425528:AAFsEhVlEyKYuHIbB96opCuH5BJIea1P-UU"
